services:
  next-app:
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - "../files/next-app/uploads:/app/uploads"
      - "../files/next-app/logs:/app/logs"
      - "./next-app:/app"
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-app.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.next-app.entrypoints=websecure"
      - "traefik.http.routers.next-app.tls.certResolver=letsencrypt"
      - "traefik.http.services.next-app.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DOMAIN=${DOMAIN:-localhost}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "24126:24125"
    volumes:
      - "../files/backend/data:/app/data"
      - "../files/backend/logs:/app/logs"
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certResolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=24125"

  mcp-server:
    build:
      context: ./fast-markdown-mcp
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "../files/storage/markdown:/app/storage/markdown"
    networks:
      - dokploy-network
    environment:
      - PYTHONPATH=/app/src

networks:
  dokploy-network:
    external: true 